import type { Story, Product, Resource, AdminUser } from './types'

export const stories: Story[] = [
  {
    id: 1,
    category: 'Adventure',
    title: 'The Last Expedition',
    description: "A cartographer's journey across unmapped territories reveals secrets buried for centuries beneath the red earth.",
    readTime: '12 min read',
    image: 'https://images.unsplash.com/photo-1713845784497-fe3d7ed176d8?w=600&h=800&fit=crop&auto=format',
    featured: true,
  },
  {
    id: 2,
    category: 'Suspense',
    title: 'The Envelope',
    description: 'A single letter arrives forty years after it was sent — and its contents begin to unravel everything she thought she knew.',
    readTime: '8 min read',
    image: 'https://images.unsplash.com/photo-1531123897727-8f129e1688ce?w=600&h=800&fit=crop&auto=format',
    featured: true,
  },
  {
    id: 3,
    category: 'Romance',
    title: 'Beneath Lagos Skies',
    description: 'Two strangers, one delayed flight, and a conversation that quietly changes the course of both their lives forever.',
    readTime: '15 min read',
    image: 'https://images.unsplash.com/photo-1669040084821-097235fe53ff?w=600&h=800&fit=crop&auto=format',
    featured: true,
  },
  {
    id: 4,
    category: 'Drama',
    title: 'The Weight of Return',
    description: 'After fifteen years abroad, Amara comes home to a family that has changed in ways no one speaks about.',
    readTime: '18 min read',
    image: 'https://images.unsplash.com/photo-1595882669314-919b3d51f2c7?w=600&h=800&fit=crop&auto=format',
    featured: false,
  },
  {
    id: 5,
    category: 'African-Inspired',
    title: "The Griot's Daughter",
    description: "Raised on stories of old kingdoms, a young woman must decide which truth is worth preserving — and which must be reborn.",
    readTime: '20 min read',
    image: 'https://images.unsplash.com/photo-1628682814595-a3f0816b25ff?w=600&h=800&fit=crop&auto=format',
    featured: false,
  },
  {
    id: 6,
    category: 'Series',
    title: 'The Ink Collective — Season 1',
    description: 'Six creators. Six cities. One story connecting them all — told in six chapters across six weeks.',
    readTime: '6 episodes',
    image: 'https://images.unsplash.com/photo-1708170236295-20ab8fbadcef?w=600&h=800&fit=crop&auto=format',
    featured: false,
  },
]

export const products: Product[] = [
  {
    id: 1,
    title: 'The Story Bible: Complete Edition',
    description: '300+ prompts, narrative frameworks, and world-building tools for creators who build story universes.',
    price: '$19',
    priceValue: 19,
    category: 'E-book',
    image: 'https://images.unsplash.com/photo-1518478582619-6633d0e36cf8?w=600&h=600&fit=crop&auto=format',
    badge: 'Bestseller',
  },
  {
    id: 2,
    title: 'YouTube Script Mastery Kit',
    description: 'Templates, hooks, and structure guides for faceless YouTube storytelling channels that retain viewers.',
    price: '$24',
    priceValue: 24,
    category: 'Creator Kit',
    image: 'https://images.unsplash.com/photo-1723723467478-eb4667116137?w=600&h=600&fit=crop&auto=format',
    badge: 'New',
  },
  {
    id: 3,
    title: '30-Day Content Planner',
    description: 'A daily creative planner with story prompts, content calendars, and reflection exercises for consistent creators.',
    price: '$12',
    priceValue: 12,
    category: 'Digital Planner',
    image: 'https://images.unsplash.com/photo-1583406405106-12a7e3236494?w=600&h=600&fit=crop&auto=format',
  },
  {
    id: 4,
    title: '100 Cinematic Story Hooks',
    description: 'Opening lines so compelling they demand to be finished. Perfect for fiction writers, YouTubers, and screenwriters.',
    price: '$9',
    priceValue: 9,
    category: 'Prompt Pack',
    image: 'https://images.unsplash.com/photo-1599939653538-2f2a713292df?w=600&h=600&fit=crop&auto=format',
  },
  {
    id: 5,
    title: 'African Narratives Collection Vol. 1',
    description: 'Twelve original short stories exploring identity, belonging, and transformation across five countries.',
    price: '$14',
    priceValue: 14,
    category: 'Story Collection',
    image: 'https://images.unsplash.com/photo-1687052093309-7a14efa58ecb?w=600&h=600&fit=crop&auto=format',
    badge: 'Featured',
  },
  {
    id: 6,
    title: 'AI Storytelling Prompt Pack',
    description: 'Engineered prompts for using AI tools to develop characters, plots, and narrative arcs at scale.',
    price: '$16',
    priceValue: 16,
    category: 'Prompt Pack',
    image: 'https://images.unsplash.com/photo-1593351799227-75df2026356b?w=600&h=600&fit=crop&auto=format',
  },
]

export const resources: Resource[] = [
  {
    id: 1,
    title: '50 Story Ideas',
    description: "Genre-spanning prompts to break through writer's block and ignite your next project.",
    format: 'PDF',
    icon: '✦',
  },
  {
    id: 2,
    title: 'YouTube Script Template',
    description: 'A proven structure for faceless storytelling videos that hook viewers in the first 30 seconds.',
    format: 'Google Doc',
    icon: '◈',
  },
  {
    id: 3,
    title: '100 Story Hooks',
    description: 'Opening lines engineered to create immediate curiosity and compel readers to continue.',
    format: 'PDF',
    icon: '◉',
  },
  {
    id: 4,
    title: '30-Day Content Planner',
    description: 'A month of structured creativity — daily story exercises, content ideas, and reflection prompts.',
    format: 'PDF',
    icon: '◇',
  },
]

export const adminUsers: AdminUser[] = [
  {
    id: 1,
    name: 'Chidi Okafor',
    email: 'chidi@theinkbity.com',
    role: 'Owner',
    joined: 'Jan 2024',
    status: 'Active',
  },
  {
    id: 2,
    name: 'Amara Diallo',
    email: 'amara@theinkbity.com',
    role: 'Editor',
    joined: 'Mar 2024',
    status: 'Active',
  },
  {
    id: 3,
    name: 'Ngo Thanh',
    email: 'ngo@theinkbity.com',
    role: 'Editor',
    joined: 'Jun 2024',
    status: 'Active',
  },
  {
    id: 4,
    name: 'Lucia Fernandez',
    email: 'lucia@theinkbity.com',
    role: 'Viewer',
    joined: 'Aug 2024',
    status: 'Pending',
  },
]
